export const rooms = [
  {
    id: "dubla-standard",
    name: "Cameră Dublă Standard",
    nameEn: "Standard Double Room",
    size: 28,
    capacity: 2,
    beds: "1 Pat Matrimonial",
    price: 350,
    currency: "RON",
    images: [
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80",
      "https://images.unsplash.com/photo-1631049035634-2d4eb8e0b2e3?w=800&q=80",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80",
    ],
    description: "O cameră elegantă cu vedere la pădure, dotată cu toate facilitățile moderne pentru un sejur confortabil.",
    amenities: ["WiFi Gratuit", "Sistem Climatizare", "TV Smart", "Minibar", "Seif"],
    category: "Standard",
    available: true,
    rating: 4.8,
    reviews: 124,
  },
  {
    id: "dubla-deluxe-cada",
    name: "Cameră Dublă Deluxe cu Cadă",
    nameEn: "Deluxe Double Room with Bathtub",
    size: 45,
    capacity: 2,
    beds: "1 Pat Matrimonial King",
    price: 532,
    currency: "RON",
    images: [
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80",
      "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
    ],
    description: "Luxul suprem într-un spațiu generos cu o cadă free-standing spectaculoasă și balcon privat cu vedere panoramică.",
    amenities: ["WiFi Gratuit", "Cadă Free-standing", "Balcon Privat", "Sistem Climatizare", "TV Smart 55\"", "Minibar Premium", "Seif", "Halate de Baie"],
    category: "Deluxe",
    available: true,
    rating: 4.9,
    reviews: 89,
    featured: true,
  },
  {
    id: "dubla-deluxe-twin",
    name: "Cameră Dublă Deluxe Twin",
    nameEn: "Deluxe Twin Room",
    size: 45,
    capacity: 2,
    beds: "2 Paturi Single",
    price: 532,
    currency: "RON",
    images: [
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800&q=80",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800&q=80",
    ],
    description: "Perfectă pentru două persoane care preferă paturie separate. Spațioasă, elegantă, cu balcon privat și toate dotările premium.",
    amenities: ["WiFi Gratuit", "2 Paturi Single", "Balcon Privat", "Sistem Climatizare", "TV Smart 55\"", "Minibar", "Seif"],
    category: "Deluxe",
    available: true,
    rating: 4.8,
    reviews: 67,
  },
  {
    id: "suite-superioare",
    name: "Suită Superioară",
    nameEn: "Superior Suite",
    size: 65,
    capacity: 3,
    beds: "1 Pat King + Canapea Extensibilă",
    price: 780,
    currency: "RON",
    images: [
      "https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
      "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&q=80",
    ],
    description: "Suita noastră de top oferă o experiență cu adevărat memorabilă cu living separat, jacuzzi și terasa privată.",
    amenities: ["WiFi Gratuit", "Living Separat", "Jacuzzi", "Terasă Privată", "Sistem Climatizare", "TV Smart 65\"", "Minibar Premium", "Seif", "Halate & Papuci", "Mic Dejun Inclus"],
    category: "Suite",
    available: true,
    rating: 5.0,
    reviews: 42,
    featured: true,
  },
];

export const facilities = [
  { icon: "⚡", title: "Încărcare EV", description: "Stații de încărcare pentru vehicule electrice" },
  { icon: "💆", title: "Spa & Wellness", description: "Tratamente de relaxare și revitalizare" },
  { icon: "🔑", title: "Acces cu Card", description: "Sistem modern de securitate cu carduri" },
  { icon: "🍷", title: "Vinotecă", description: "Selecție premium de vinuri locale" },
  { icon: "🍺", title: "Beer Garden", description: "Grădină de vară cu bere artizanală" },
  { icon: "🏊", title: "Activități Sport", description: "Piscină, tenis, biciclete, ATV" },
  { icon: "🍽️", title: "Restaurant", description: "Bucătărie tradițională bucovineană" },
  { icon: "🚗", title: "Parcare Gratuită", description: "Parcare supravegheată video" },
];

export const testimonials = [
  {
    name: "Maria Ionescu",
    location: "București",
    rating: 5,
    date: "Octombrie 2024",
    text: "O experiență de neuitat! Camera cu cadă a fost absolut spectaculoasă, iar personalul extrem de amabil. Bucovina la superlativ. Vom reveni cu siguranță!",
    avatar: "M",
  },
  {
    name: "Alexandru Popa",
    location: "Cluj-Napoca",
    rating: 5,
    date: "Septembrie 2024",
    text: "Hanul Bucovinei este locul perfect pentru o escapadă romantică. Designul camerei, priveliștea, mâncarea – totul a fost impecabil. 10/10!",
    avatar: "A",
  },
  {
    name: "Elena & Mihai Dobre",
    location: "Iași",
    rating: 5,
    date: "August 2024",
    text: "Ne-am petrecut aniversarea de 10 ani aici și nu am fi putut alege un loc mai bun. Atmosfera, liniștea, serviciile – totul la cel mai înalt nivel.",
    avatar: "E",
  },
  {
    name: "Cristian Radu",
    location: "Timișoara",
    rating: 4,
    date: "Iulie 2024",
    text: "Locație superb, camere frumos decorate. Micul dejun a fost un deliciu cu produse locale proaspete. Recomand cu căldură!",
    avatar: "C",
  },
  {
    name: "Ana Constantin",
    location: "Brașov",
    rating: 5,
    date: "Iunie 2024",
    text: "Am venit cu familia și a fost o vacanță perfectă. Copiii au adorat activitățile, iar noi ne-am relaxat la spa. Vom reveni!",
    avatar: "A",
  },
];

export const faqs = [
  {
    q: "Care este ora de check-in și check-out?",
    a: "Check-in: 15:00 | Check-out: 12:00. Late check-out disponibil la cerere, în funcție de disponibilitate.",
  },
  {
    q: "Anularea rezervării este gratuită?",
    a: "Da! Oferiți anulare gratuită până la 7 zile înainte de check-in. Pentru rezervările de ultimă oră, vă rugăm să contactați recepția.",
  },
  {
    q: "Sunt acceptate animale de companie?",
    a: "Acceptăm animale de companie mici (sub 10kg) în camerele Standard, cu un supliment de 50 RON/noapte. Vă rugăm să menționați la rezervare.",
  },
  {
    q: "Există parcare la han?",
    a: "Da, dispunem de parcare gratuită supravegheată video pentru toți oaspeții noștri, inclusiv stații de încărcare EV.",
  },
  {
    q: "La ce distanță sunt principalele obiective turistice?",
    a: "Mânăstirile din Bucovina (Sucevița, Moldovița) sunt la 20-40 km. Câmpulung Moldovenesc la 15 km. Suceava la 50 km.",
  },
  {
    q: "Oferiți servicii de transfer?",
    a: "Oferim transfer de la/la Gara Câmpulung Moldovenesc și Aeroportul Suceava (Salcea), contra cost. Contactați-ne pentru detalii.",
  },
];

export const galleryImages = [
  { src: "https://images.unsplash.com/photo-1610881648560-3581562ef831?w=800&q=80", alt: "Exterior han" },
  { src: "https://images.unsplash.com/photo-1600011689032-8b628b8a8747?w=800&q=80", alt: "Camera deluxe" },
  { src: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80", alt: "Interior living" },
  { src: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80", alt: "Restaurant" },
  { src: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80", alt: "Spa" },
  { src: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80", alt: "Piscina" },
  { src: "https://images.unsplash.com/photo-1551882547-ff40c4a49f5d?w=800&q=80", alt: "Vedere panoramica" },
  { src: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80", alt: "Masa bucatariei" },
];
